1.33.246.siab_Production_Build

diff --git a/perl/agents/vmu_PreAssessment_launcher b/perl/agents/vmu_PreAssessment_launcher
--- a/perl/agents/vmu_PreAssessment_launcher
+++ b/perl/agents/vmu_PreAssessment_launcher
@@ -5,5 +5,43 @@
 #
 # Copyright 2012-2018 Software Assurance Marketplace
 
-export PATH=/opt/perl5/perls/perl-5.18.1/bin:$PATH
-sudo /opt/perl5/perls/perl-5.18.1/bin/perl /opt/swamp/bin/vmu_PreAssessment.pl "$@"
+execrunuid=$1
+logfile="/opt/swamp/log/htcondor_launcher_${execrunuid}.log"
+
+echo -e "$0 [$$]\n$@\nstarted at: `date`" >> $logfile
+
+echo -n "id: " >> $logfile
+id >> $logfile
+
+# echo "env: " >> $logfile
+# env >> $logfile
+
+echo -n "pwd: " >> $logfile
+pwd >> $logfile
+ls -l >> $logfile
+
+echo "perl: " >> $logfile
+ls -l /opt/perl5/perls/perl-5.18.1/bin/perl >> $logfile
+
+# echo "/opt/swamp/bin: " >> $logfile
+# ls -l /opt/swamp/bin >> $logfile
+
+echo "" >> $logfile
+
+sudo /opt/perl5/perls/perl-5.18.1/bin/perl /opt/swamp/bin/vmu_PreAssessment.pl "$@" >> $logfile 2>&1
+result=$?
+echo "exit result: $result" >> $logfile
+
+# try to signal htcondor to not start the vm if the PreCmd failed
+if [ "$result" -ne 0 ]
+then
+	echo "Unlinking qcow2 files (delta, inputdisk, outputdis)" >> $logfile
+	unlink delta.qcow2 >> $logfile
+	unlink inputdisk.qcow2 >> $logfile
+	unlink outputdisk.qcow2 >> $logfile
+fi
+
+echo "" >> $logfile
+
+# return result from command or its children
+exit $result
